#!/usr/bin/env ruby
#
# Runs the PodioKit unit test suite.
#
# Usage:
#
# ./run-tests [--device <ipad|iphone>] [--sdk <6.0|7.0>] [--raw]
#

require 'getoptlong'

SCHEME = 'PodioKit'
WORKSPACE = 'PodioKit.xcworkspace'

def destination_for_device(device = nil)
  device_name = case device
    when 'ipad' then 'iPad Retina'
    else 'iPhone Retina (4-inch)'
  end
  
  return "platform=iOS Simulator,name=#{device_name}"
end

opts = GetoptLong.new(
  ['--device', GetoptLong::OPTIONAL_ARGUMENT],
  ['--sdk', GetoptLong::OPTIONAL_ARGUMENT],
  ['--raw', GetoptLong::OPTIONAL_ARGUMENT]
)

destination = destination_for_device()
sdk_version = nil
raw = false

opts.each do |opt, arg|
  case opt
    when '--device'
      destination = destination_for_device(arg)
    when '--sdk'
      sdk_version = arg || nil
    when '--raw'
      raw = true
  end
end

cmd = "xcodebuild -scheme #{SCHEME} -workspace #{WORKSPACE} -destination \"#{destination}\""
cmd << " -sdk \"iphonesimulator#{sdk_version}\"" if sdk_version
cmd << " test"
cmd << "| xcpretty -c; exit ${PIPESTATUS[0]}" unless raw

code = system(cmd)
exit code if code != 0